### ISSUE TITLE
Isn't this already a native feature?

### ISSUE THREAD

**Issue by slxdy** [SamboyCoding/MultiMelonExample#1]
Found this repo through the homepage and got curious. But from what I remember, I did allow a single assembly to contain multiple melon classes already

**Comment by SamboyCoding** [comment]
No, the attribute isn't allowed to be added multiple times.

**Comment by slxdy** [comment]
Wait fr? Why did I add the functionality then lol. Could change that for 0.6.5 then maybe? Otherwise it's a waste
